import hashlib
import hmac
import json
from pathlib import Path

from fastapi import Header, HTTPException

from .audit_log import log_event

_CLIENTS_PATH = Path(__file__).parent / "clients.json"


def _load_clients() -> dict:
    if not _CLIENTS_PATH.exists():
        return {}
    with _CLIENTS_PATH.open() as f:
        return json.load(f)


# Local client registry, generated by scripts/generate_client_key.py.
# Never contains plaintext keys — only their hashes. Not committed to git;
# a real deployment would swap this module for a proper secrets store.
_CLIENTS = _load_clients()


def _hash_key(api_key: str) -> str:
    # Not a password hash: api_key is a 256-bit random token (secrets.token_urlsafe),
    # not a human-chosen low-entropy secret, so there's no guessable search space for
    # a slow/adaptive hash (bcrypt/argon2) to protect against - a fast hash is correct
    # here, the same way GitHub/AWS hash their own high-entropy tokens.
    return hashlib.sha256(api_key.encode("utf-8")).hexdigest()  # lgtm[py/weak-sensitive-data-hashing]


def authenticate(authorization: str | None = Header(default=None)) -> str:
    if authorization is None or not authorization.startswith("Bearer "):
        log_event(
            "auth_failure",
            client_id=None,
            outcome="blocked",
            detail={"reason": "missing_or_malformed_header"},
        )
        raise HTTPException(status_code=401, detail="missing or malformed Authorization header")

    api_key = authorization.removeprefix("Bearer ").strip()
    key_hash = _hash_key(api_key)

    for client_id, record in _CLIENTS.items():
        if hmac.compare_digest(record["key_hash"], key_hash):
            return client_id

    # client_id is intentionally omitted here, not just unknown: the only
    # client_id available at this point would be one an attacker claims in
    # the request body, unverified. Logging it as fact would let anyone
    # frame a real client in the audit trail for a failure that was theirs.
    log_event("auth_failure", client_id=None, outcome="blocked", detail={"reason": "invalid_key"})
    raise HTTPException(status_code=401, detail="invalid API key")
