import hashlib
import hmac
import json
from pathlib import Path

from fastapi import Header, HTTPException

_CLIENTS_PATH = Path(__file__).parent / "clients.json"


def _load_clients() -> dict:
    if not _CLIENTS_PATH.exists():
        return {}
    with _CLIENTS_PATH.open() as f:
        return json.load(f)


# Local client registry, generated by scripts/generate_client_key.py.
# Never contains plaintext keys — only their hashes. Not committed to git;
# a real deployment would swap this module for a proper secrets store.
_CLIENTS = _load_clients()


def _hash_key(api_key: str) -> str:
    return hashlib.sha256(api_key.encode("utf-8")).hexdigest()


def authenticate(authorization: str | None = Header(default=None)) -> str:
    if authorization is None or not authorization.startswith("Bearer "):
        raise HTTPException(status_code=401, detail="missing or malformed Authorization header")

    api_key = authorization.removeprefix("Bearer ").strip()
    key_hash = _hash_key(api_key)

    for client_id, record in _CLIENTS.items():
        if hmac.compare_digest(record["key_hash"], key_hash):
            return client_id

    raise HTTPException(status_code=401, detail="invalid API key")
